# Simulation Parameters
simulation:
  total_ticks: 80000
  seed: 42  # For reproducibility
  hide_layer_index: 0
  log_interval: 500
  verbose: true

# Causal Site (Graph) Parameters
causal_site:
  layers: 60
  avg_nodes_per_layer: 35
  edge_probability: 0.08
  max_lookback_layers: 2

# State & Tag Parameters
tags:
  alphabet_size_q: 23
  max_out_degree_R: 2
  fusion_mode: "injective" # 'quadratic' or 'injective' or 'sum_mod_q'

# Particle Detection Parameters
detector:
  grid_size: 30  # Divide the site into 10x10 cells for hashing
  max_history_length: 60000 # Memory optimization for hash history
  min_loop_period: 3
  min_particle_size: 2 # Minimum number of cells in a cluster

# Visualization Parameters
visualization:
  enabled: true
  update_interval: 100 # Update the plot every 10 ticks
  save_frames: true

  


